"""KAIRO Database Package."""

from app.db.database import init_db, close_db, get_session, get_session_dependency, Base
from app.db.models import (
    Store,
    Product,
    ProductAttribute,
    Inventory,
    Reservation,
    ReservationItem,
    ReservationStatus,
    Session,
    SessionStatus,
    ConversationMessage,
    MessageRole,
    AgentEvent,
    ToolExecution,
    EventType,
)
from app.db.repositories import (
    StoreRepository,
    ProductRepository,
    InventoryRepository,
    ReservationRepository,
    SessionRepository,
    EventRepository,
    ToolExecutionRepository,
)

__all__ = [
    "init_db",
    "close_db",
    "get_session",
    "get_session_dependency",
    "Base",
    "Store",
    "Product",
    "ProductAttribute",
    "Inventory",
    "Reservation",
    "ReservationItem",
    "ReservationStatus",
    "Session",
    "SessionStatus",
    "ConversationMessage",
    "MessageRole",
    "AgentEvent",
    "ToolExecution",
    "EventType",
    "StoreRepository",
    "ProductRepository",
    "InventoryRepository",
    "ReservationRepository",
    "SessionRepository",
    "EventRepository",
    "ToolExecutionRepository",
]